// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVCintcNIAyqPmga2l1NZzBsKEkIMRfew',
    appId: '1:896686770545:web:b65a0f679f7e1a6175ced0',
    messagingSenderId: '896686770545',
    projectId: 'mentorchatapp',
    authDomain: 'mentorchatapp.firebaseapp.com',
    storageBucket: 'mentorchatapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdGJCo8qLft2bc31DrkzEOeUBBz-vKJT0',
    appId: '1:896686770545:android:16c0f31900dae4b875ced0',
    messagingSenderId: '896686770545',
    projectId: 'mentorchatapp',
    storageBucket: 'mentorchatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcC7JqjicDIljeWZ7-xP-MLeMfCrGU6kg',
    appId: '1:896686770545:ios:714ada3c2fc4513b75ced0',
    messagingSenderId: '896686770545',
    projectId: 'mentorchatapp',
    storageBucket: 'mentorchatapp.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcC7JqjicDIljeWZ7-xP-MLeMfCrGU6kg',
    appId: '1:896686770545:ios:714ada3c2fc4513b75ced0',
    messagingSenderId: '896686770545',
    projectId: 'mentorchatapp',
    storageBucket: 'mentorchatapp.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVCintcNIAyqPmga2l1NZzBsKEkIMRfew',
    appId: '1:896686770545:web:9fab9e004879c43f75ced0',
    messagingSenderId: '896686770545',
    projectId: 'mentorchatapp',
    authDomain: 'mentorchatapp.firebaseapp.com',
    storageBucket: 'mentorchatapp.firebasestorage.app',
  );
}
